vim.opt.rtp:prepend(vim.fn.getcwd())
local root = vim.fn.tempname()
vim.fn.mkdir(root .. "/src/nested", "p")
vim.fn.writefile({ "hello" }, root .. "/src/nested/example.lua")
vim.fn.writefile({ "hello" }, root .. "/space name.txt")
local paths = require("aero.acp.paths")
local items
paths.items(root, function(found) items = found end)
assert(vim.wait(3000, function() return items ~= nil end))
local keys = {}
for _, item in ipairs(items) do keys[item.key] = true end
assert(keys["src/"] and keys["src/nested/"] and keys["src/nested/example.lua"])
assert(vim.fn.matchfuzzy(items, "sne", { key = "key" })[1].key:find("src/nested", 1, true))
local start, query = paths.token("Review @sne")
assert(start == 8 and query == "sne")
assert(paths.token("email@example.com") == nil)
assert(paths.token('Review @"space name.txt" ') == nil)
assert(paths.token("Review @src/ ") == nil)
local matches = paths.candidates(items, "sne")
assert(matches[1].word:find("@src/nested", 1, true) == 1)
assert(matches[1].equal == 1)
assert(paths.candidates(items, "space")[1].word == '@"space name.txt" ')
assert(#paths.candidates(items, "no-matching-path") == 0)
local folders = paths.candidates({ { key = "src/" } }, "")
assert(folders[1].word == "@src/ " and folders[1].menu == "Folder")
vim.fn.delete(root, "rf")
print("prompt paths: ok")
vim.cmd.qa({ bang = true })
