-- Run: nvim --headless -u NONE -l tests/tasks_removed_board.lua
vim.opt.rtp:prepend(vim.fn.getcwd())
local root = vim.fn.tempname()
vim.fn.mkdir(root, "p")
require("aero").setup({ tasks = { directory = "worktree", states = { "todo", "done" } } })
local ws = { root = root }
local tasks = require("aero.tasks")
local storage = require("aero.tasks.storage")
local source = assert(tasks.create_board(ws, "Source"))
local target = assert(tasks.create_board(ws, "Target"))
local ticket = assert(tasks.create_ticket(ws, source.path, "todo", "Keep requirements"))
local active = assert(tasks.create_ticket(ws, source.path, "todo", "Active"))
assert(tasks.remove_ticket(ws, source.path, ticket.path))
local text = storage.read(ticket.path)
assert(tasks.delete_board(ws, source.path))
assert(not vim.uv.fs_stat(source.path) and not vim.uv.fs_stat(active.path))
local removed = tasks.list_removed(ws)
assert(#removed == 1 and storage.read(removed[1].path) == text)
assert(#tasks.list(ws) == 1)
local restored = assert(tasks.recover_ticket(ws, removed[1].board_path, removed[1].path, target.path, "done"))
assert(tasks.read_ticket(target.path, restored.path).metadata.id == ticket.metadata.id)
assert(#tasks.list_removed(ws) == 0)
-- The retained files also support permanent deletion from the workspace list.
local other = assert(tasks.create_board(ws, "Other"))
local discarded = assert(tasks.create_ticket(ws, other.path, "todo", "Discard"))
assert(tasks.remove_ticket(ws, other.path, discarded.path))
assert(tasks.delete_board(ws, other.path))
removed = tasks.list_removed(ws)
removed[1].text = removed[1].ticket.text
assert(tasks.delete_removed(ws, removed))
assert(#tasks.list_removed(ws) == 0)
vim.fn.delete(root, "rf")
print("Removed tickets survive board deletion and support recovery and permanent deletion.")
vim.cmd("qa!")
